### ISSUE TITLE
Overriding "configureMessageConverters" in spring 

### ISSUE THREAD

**Issue by rasa-app** [FusionAuth/fusionauth-jwt#39]
When I override ```configureMessageConverters``` in Spring:

```java
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {

        ObjectMapper mapper = new ObjectMapper();

        mapper.registerModule(new Hibernate5Module());
        mapper.registerModule(new JavaTimeModule());
        
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

        converters.add(new MappingJackson2HttpMessageConverter(mapper));

    }
```
The Verifier throws this exception:

```io.fusionauth.jwt.InvalidJWTException: The encoded JWT is not properly Base64 encoded.```

**Comment by voidmain** [comment]
This is likely a bug with Spring since `fusionauth-jwt` implements the JWT specification directly. If you want to provide additional details including the full stack trace, the code where you are using `fusionauth-jwt`, and your Spring configuration, we can determine if this bug is in `fusionauth-jwt`. 

I'm 99.999% certain it isn't, so you might want to open a bug with Spring as well. ;)

**Comment by robotdan** [comment]
Closing this for now, assuming this is a bug with whomever is handling the JWT and likely not preserving the proper encoding. Please re-open if you can put together a test to demonstrate a bug in this library.
